### PR TITLE
added previewer for shp, geotiff and extended geojson

### PR DESCRIPTION
**Pull request by schorcht-ioer**
Dear community,

these are previewers for some geodata formats (Esri Shape files, Geotiffs and an extended version of Geojson).

All previewers have a spinner and a file size limit. If the file size limit is exceeded, an error is thrown.

### geotiffs
With geotiffs it is also possible to define a maximum number of rows and columns (since compressed tiffs can have a small data size but still be too large to view). Since no special mimetype was available for geotiffs (only tiff), an error is thrown in case of missing projection information (or unsupported tiff variants). Also, there is a problem with the geotiff reader used that an error cannot be caught :\ Therefore, a timeout was defined in which the raster should be loaded (if not, an error is thrown).

### mimetypes
Apropos mimetpyes, can someone tell me how to customize mimetypes?
Because I would like to define mimetypes for zipped gdb (Esri Geodatabase) and geotiffs. Then geotiffs could be distinguished from "normal" tiffs (and maybe *.ovr data could be handled). Also for gdb another previewer could be included.

cheers,
martin

### CODE REVIEW

**Comment by pdurbin** [comment]
@schorcht-ioer hi! Just a quick note to say that while I haven't played with your code, I'm excited about the possibilities!

I mentioned your pull request to @atrisovic and @JR-1991 during a NetCDF/geospatial meeting this morning.

I'm not sure if @qqmyers has taken a look yet.

As for your question about mimetypes, I agree it would be better to have something more specific than `"contentType":"image/tiff"`. Maybe we could look here for inspiration:

- https://github.com/opengeospatial/geotiff/issues/34

**Comment by schorcht-ioer** [comment]
Hi @pdurbin! Thanks for your reply. The discussion about geotiff on opengeospatial is very interesting! We will see how it goes on :)

**Comment by qqmyers** [comment]
@schorcht-ioer - thanks for the contribution! A few requests for updating the PR: 
- per the [CONTRIBUTING.md](https://github.com/gdcc/dataverse-previewers/blob/master/CONTRIBUTING.md), could you make a PR against the develop branch and put your new material in the previewers/betatest folder (and make your curl commands point there)?
- It looks like your adding two new previewers and updating the existing GeoJson previewer - have you been in contact with it's creator (@kaitlinnewson)? To merge, I'd like to make sure that Kaitlin is OK with your changes (my guess is she would be. If not, it might make sense to make an alternate previewer rather than replace it.)
- W.r.t. mimetypes - adding recognition for new types would have to be done in the Dataverse repo. Until that happens, if the curl command is registering this for all image/tiff files and if it is going to fail for normal tiffs, it might be worth a comment above that command to make admins aware of this.

**Comment by schorcht-ioer** [comment]
Hi @qqmyers! Thank you for the advice. I will create a new PR for Geotiff and Shp in previewers/betatest folder. As soon as @kaitlinnewson has given her consent, I will create another PR for the existing geojson previewer, or provide an alternative version if necessary.

**Comment by pdurbin** [comment]
I'm just noting that this was closed in favor of this one:

- #36

Thanks, @schorcht-ioer!!

**Pull request closed without merging**
